name: AzisabaGift
version: @version@
main: net.azisaba.gift.spigot.SpigotPlugin
commands:
  promo:
    permission: azisabagift.command.promo
  azisabagift:
    permission: azisabagift.command.azisabagift
