name: AzisabaGift
version: @version@
main: net.azisaba.gift.spigot.SpigotPlugin
softdepend:
  - TaxOffice
  - PlayerPoints
commands:
  promo:
    permission: azisabagift.command.promo
    usage: /promo <code>
  azisabagift:
    permission: azisabagift.command.azisabagift
    usage: /<command> [args]
